version: '3.8'

services:
  # PostgreSQL database service
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"


  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: 'unless-stopped'
    ports:
      - '80:80'
      - '443:443'
      - '8090:81'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt


# Define volumes for persistence
volumes:
  pgdata:
  data:
  letsencrypt: